# Generated by Django 5.0.6 on 2024-06-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('district', models.CharField(choices=[('bundibugyo', 'Bundibugyo'), ('gulu', 'Gulu'), ('jinja', 'Jinja'), ('kabarole', 'Kabarole'), ('kampala', 'Kampala'), ('lira', 'Lira'), ('masaka', 'Masaka'), ('mpigi', 'Mpigi'), ('mukono', 'Mukono'), ('soroti', 'Soroti'), ('wakiso', 'Wakiso')], max_length=20)),
                ('country', models.CharField(choices=[('uganda', 'Uganda'), ('tanzania', 'Tanzania'), ('kenya', 'Kenya')], max_length=20)),
                ('knowledge', models.JSONField()),
                ('experience', models.JSONField()),
                ('achievements', models.TextField()),
                ('references', models.TextField()),
                ('user_type', models.CharField(default='expert', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=255)),
                ('user_type', models.CharField(default='entrepreneur', max_length=20)),
                ('role_in_company', models.CharField(choices=[('founder', 'Founder'), ('owner', 'Owner'), ('director', 'Director')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_idea', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_market', models.TextField()),
                ('consultation_time', models.TimeField()),
                ('consultation_date', models.DateField()),
                ('urgency_level', models.CharField(max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
