# Generated by Django 5.0.6 on 2024-06-19 12:57

from django.db import migrations
from django.contrib.auth.models import User

def create_default_admin(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'admin')

class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_admin),
    ]
