# Generated by Django 5.0.6 on 2024-06-25 09:03
from django.contrib.auth.models import User
from django.db import migrations
def create_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'admin')

class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]



