# Generated by Django 5.0.6 on 2024-07-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0002_auto_20240625_1203'),
        ('Bizconnect', '0002_create_default_admin_user'),
    ]

    operations = [
    ]
