# Generated by Django 5.0.6 on 2024-06-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0002_registration_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('district', models.CharField(choices=[('bundibugyo', 'Bundibugyo'), ('gulu', 'Gulu'), ('jinja', 'Jinja'), ('kabarole', 'Kabarole'), ('kampala', 'Kampala'), ('lira', 'Lira'), ('masaka', 'Masaka'), ('mpigi', 'Mpigi'), ('mukono', 'Mukono'), ('soroti', 'Soroti'), ('wakiso', 'Wakiso')], max_length=20)),
                ('country', models.CharField(choices=[('uganda', 'Uganda'), ('tanzania', 'Tanzania'), ('kenya', 'Kenya')], max_length=20)),
                ('experience', models.JSONField()),
                ('knowledge', models.JSONField()),
                ('achievements', models.TextField()),
                ('references', models.TextField()),
                ('user_type', models.CharField(default='expert', max_length=20)),
            ],
        ),
    ]
