# Generated by Django 5.0.6 on 2024-06-26 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0003_merge_20240626_1136'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bizconnect.registration'),
        ),
        migrations.CreateModel(
            name='InvestmentDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.TextField()),
                ('entreprenuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bizconnect.registration')),
            ],
        ),
    ]
