# Generated by Django 5.0.6 on 2024-06-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0007_scheduledmeeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
