# Generated by Django 5.0.3 on 2024-07-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0007_investmentfunds'),
        ('Bizconnect', '0008_scheduledmeeting_denial_reason'),
    ]

    operations = [
    ]
