# Generated by Django 5.0.3 on 2024-07-02 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0009_merge_20240701_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessideas',
            name='entrepreneur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_ideas', to='Bizconnect.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='entrepreneur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investment_deals', to='Bizconnect.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentfunds',
            name='entrepreneur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investment_fund', to='Bizconnect.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='entrepreneur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_meeting', to='Bizconnect.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='entrepreneur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='Bizconnect.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investmentfunds',
            name='type',
            field=models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('convertible_note', 'Convertible Note')], max_length=100),
        ),
    ]
