# Generated by Django 5.0.3 on 2024-07-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0011_remove_servicerequest_entrepreneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdeal',
            name='entrepreneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bizconnect.registration'),
        ),
    ]
