# Generated by Django 5.0.6 on 2024-07-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bizconnect', '0009_investmentfunds_investor'),
        ('Bizconnect', '0012_alter_investmentdeal_entrepreneur'),
    ]

    operations = [
    ]
